### ISSUE TITLE
Worklogdebt exception handling

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#59]
## Description

The Worklogdebt microservice needs to improve its exception handling mechanism to provide better feedback to users when errors occur. Currently, when an exception is thrown in the service, the error message is not clear enough for users to understand what went wrong.

The goal of this issue is to enhance the Worklogdebt service's exception handling by adding custom exception classes that provide more descriptive error messages. Additionally, we need to update the API responses with appropriate HTTP status codes to make error messages more meaningful to the end-users.

## Tasks

- [x] Create custom exceptions for common error cases in the worklogdebt service with the correct hierarchy
- [x] Create exception handling classes for the application layer
- [x] Create exception handling classes for the adapter layer
- [x] Update the API responses to include appropriate HTTP status codes and error messages

**Comment by letimofeev** [comment]
Done
