### ISSUE TITLE
Create Microservices Architecture Schema and Update README.md

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#70]
## Description
Create a schema that outlines the architecture of our microservices and update the README.md file with relevant information. The 
the schema should include the different microservices that exist now, how they interact with each other, and any dependencies between them.

## Tasks

- [x] Create a schema that outlines the architecture of our microservices.
- [x] Update the README.md file with relevant information about the microservices and their interactions.
- [x] Review and test the updated README.md file.

**Comment by letimofeev** [comment]
Done
