### ISSUE TITLE
Implement API Gateway

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#78]
## Description

Need to implement an API Gateway for the application to handle all incoming requests and route them to the appropriate microservice. This will provide a centralized entry point for the application and allow us to manage the traffic flow more efficiently

## Tasks

- [x] Create and configure Spring Cloud Gateway
- [x] Define the routes for each microservice in the API Gateway configuration
- [x] Add Dockerfile and GitHub Actions pipeline to build and push docker image

**Comment by letimofeev** [comment]
Done
