### ISSUE TITLE
 Create a Spring Boot starter with common exceptions handling

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#80]
## Description
Need to create a Spring Boot starter that includes a common @ControllerAdvice class to handle exceptions like NoHandlerFoundException and BindException. This would make it easier to handle these exceptions in microservices without having to copy and paste the same code

## Tasks
- [x] Add spring boot starter with common exceptions handling
- [x] Add tests and javadocs
- [x] Add starter to employee service and make sure that all work correct
- [x] Add starter to ci pipeline, refactor workflows for services to include starter as dependency

**Comment by letimofeev** [comment]
Done
