### ISSUE TITLE
Add Region service

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#86]
## Description
The `region` microservice is needed to manage information about regions in the project. The microservice will be responsible for creating, updating, deleting, and querying regions. Other microservices, such as `employee` and `vacation`, will depend on `region` to ensure consistency of region information across the project.

## Tasks
- [x] Create a new microservice for `region` that will be deployed separately.
- [x] Add the necessary code and configuration files to the project.
- [x] Create API endpoints for `region` to allow other microservices to interact with it.
- [x] Implement event-driven architecture to synchronize information about regions across microservices.

## Requirements
The `region` microservice has the following requirements:

- Store and retrieve region information from a database.
- Provide a REST API for other microservices to interact with.
- Publish and subscribe to events to keep region information consistent across microservices.

**Comment by letimofeev** [comment]
Done
