### ISSUE TITLE
Integrate employee with region

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#88]
## Description 
As part of the system, we need to add the capability to associate an employee with a region. For this, we'll need to integrate the employee microservice with the region microservice. Also, we need to ensure that the region data in the employee database is synchronized with the region microservice using RabbitMQ events

## Tasks
- [x] Add Region field to Employee entity
- [x] Implement the RabbitMQ event listener in the employee microservice to consume events from the region microservice
- [x] Update REST API in the employee microservice to create and update an employee with region information
- [x] Ensure that the region data in the employee database is synchronized with the region microservice using RabbitMQ events
- [x] Update docs and swagger specification
