### ISSUE TITLE
Grouping notification fields in Employee into object

### ISSUE THREAD

**Issue by letimofeev** [letimofeev/worklog-reminder#92]
## Description
Currently, in Employee domain object, there are two fields, notificationEnabled and botConnected, which indicate whether an employee has enabled notifications and whether the employee's bot is connected, respectively. We would like to group these fields into a new object

## Tasks
- [x] Create a new NotificationStatus object
- [x] Update the Employee entity to use the NotificationStatus object instead of the notificationEnabled and botConnected fields
- [x] Implement logic to populate the NotificationStatus object
- [x] Update tests
- [x] Update WorklogDebt service
- [x] Update the documentation and Swagger specification to reflect the changes
